services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    environment:
      - PORT=3000
      - UPLOAD_PATH=./uploads
      - EXTERNAL_API_URL=https://viacep.com.br/ws

volumes:
  uploads_data:
